#!/usr/bin/env python3
"""Import legacy Excel sheets into D1 compatibility SQL.

Usage:
  python scripts/import_legacy_excel.py legacy.xlsx > legacy_import.sql
  python scripts/import_legacy_excel.py legacy.xlsx --dataset News > news.sql

The workbook must contain sheets named:
Executive, News, Announcements, Knowledge, Banners, ITA, Downloads,
About, Systems, Popup. Complaints is intentionally not imported here because
its Phase 1 target is the structured D1 complaints table.

Every imported cell is converted to a string. row_index is zero-based among
legacy data rows (Excel row 2 => row_index 0), matching the compatibility
contract rather than the spreadsheet's physical row number.
"""
from __future__ import annotations

import argparse
import json
import math
from datetime import date, datetime, time
from pathlib import Path

from openpyxl import load_workbook

DATASETS = [
    'Executive', 'News', 'Announcements', 'Knowledge', 'Banners', 'ITA',
    'Downloads', 'About', 'Systems', 'Popup'
]


def cell_string(cell) -> str:
    value = cell.value
    if value is None:
        return ''
    if isinstance(value, bool):
        return 'TRUE' if value else 'FALSE'
    if isinstance(value, datetime):
        return value.strftime('%d/%m/%Y %H:%M:%S')
    if isinstance(value, date):
        return value.strftime('%d/%m/%Y')
    if isinstance(value, time):
        return value.strftime('%H:%M:%S')
    if isinstance(value, float):
        if math.isfinite(value) and value.is_integer():
            return str(int(value))
    return str(value)


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('workbook', type=Path)
    parser.add_argument('--dataset', choices=DATASETS, action='append')
    parser.add_argument('--clear', action='store_true', help='Emit DELETE statements before inserting rows')
    args = parser.parse_args()

    selected = args.dataset or DATASETS
    wb = load_workbook(args.workbook, read_only=True, data_only=True)
    now = datetime.utcnow().isoformat(timespec='seconds') + 'Z'

    print('-- Generated by import_legacy_excel.py')
    print('-- IMPORTANT: verify against the original Google Sheets display values before production cutover.')
    print('PRAGMA foreign_keys = ON;')

    for dataset in selected:
        if dataset not in wb.sheetnames:
            raise SystemExit(f'Missing worksheet: {dataset}')
        ws = wb[dataset]
        if args.clear:
            print(f'DELETE FROM legacy_rows WHERE dataset = {sql_quote(dataset)};')
        for row_index, row in enumerate(ws.iter_rows(min_row=2, values_only=False)):
            values = [cell_string(cell) for cell in row]
            while values and values[-1] == '':
                values.pop()
            # Keep completely blank data rows out of D1, matching getSheetData's
            # practical use while preserving row_index for all nonblank rows.
            if not any(values):
                continue
            payload = json.dumps(values, ensure_ascii=False, separators=(',', ':'))
            print(
                'INSERT INTO legacy_rows(dataset,row_index,data_json,created_at,updated_at) '
                f'VALUES ({sql_quote(dataset)},{row_index},{sql_quote(payload)},{sql_quote(now)},{sql_quote(now)}) '
                'ON CONFLICT(dataset,row_index) DO UPDATE SET '
                'data_json=excluded.data_json,updated_at=excluded.updated_at;'
            )

            if dataset in ('News', 'Announcements'):
                view_index = 5 if dataset == 'News' else 4
                initial = 0
                if len(values) > view_index:
                    try:
                        initial = int(float(values[view_index] or 0))
                    except ValueError:
                        initial = 0
                print(
                    'INSERT INTO legacy_views(dataset,legacy_row_id,view_count,updated_at) '
                    f'SELECT {sql_quote(dataset)},id,{initial},{sql_quote(now)} FROM legacy_rows '
                    f'WHERE dataset={sql_quote(dataset)} AND row_index={row_index} '
                    'ON CONFLICT(dataset,legacy_row_id) DO UPDATE SET '
                    'view_count=excluded.view_count,updated_at=excluded.updated_at;'
                )

    print('-- End import')


if __name__ == '__main__':
    main()
