-- ITA 12 เดือน 2569 : import metadata to D1
-- Run AFTER files are uploaded to GitHub main under /ita-12m-2569/

INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 175, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 4", "MOIT4 รายงานผลของแผนการจัดซื้อจัดจ้างและการ", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit04_01.doc"]', 'MOIT4 รายงานผลของแผนการจัดซื้อจัดจ้างและการ');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 176, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 5", "MOIT5 ไตรมาส3 พ.ค.69", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit05_01.doc"]', 'MOIT5 ไตรมาส3 พ.ค.69');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 177, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 5", "MOIT5 ไตรมาส3 มิ.ย.69", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit05_02.doc"]', 'MOIT5 ไตรมาส3 มิ.ย.69');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 178, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 5", "MOIT5 ไตรมาส3 เม.ย69", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit05_03.doc"]', 'MOIT5 ไตรมาส3 เม.ย69');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 179, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 5", "MOIT5 ไตรมาส4 ก.ค.69", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit05_04.doc"]', 'MOIT5 ไตรมาส4 ก.ค.69');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 180, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 5", "MOIT5 ไตรมาส4 ส.ค.69", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit05_05.doc"]', 'MOIT5 ไตรมาส4 ส.ค.69');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 181, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 7", "OK MOIT 7 หนังสือแจ้ง+ประกาศ ดีเด่น+ดีมาก รอบที่ 2-", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit07_01.pdf"]', 'OK MOIT 7 หนังสือแจ้ง+ประกาศ ดีเด่น+ดีมาก รอบที่ 2-');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 182, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 9", "9 MOIT แบบฟอร์มเผยแพร่บนเว็บไซต์2569", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit09_01.docx"]', '9 MOIT แบบฟอร์มเผยแพร่บนเว็บไซต์2569');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 183, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 10", "9 MOIT แบบฟอร์มเผยแพร่บนเว็บไซต์2569", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit10_01.docx"]', '9 MOIT แบบฟอร์มเผยแพร่บนเว็บไซต์2569');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 184, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 10", "9 MOIT แบบฟอร์มเผยแพร่บนเว็บไซต์2569", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit10_02.pdf"]', '9 MOIT แบบฟอร์มเผยแพร่บนเว็บไซต์2569');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 185, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 10", "MOIT10 บันทึกรายงานผลการดำเนินงานเรื่องร้องเรียน รอบ 12 เดือน", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit10_03.doc"]', 'MOIT10 บันทึกรายงานผลการดำเนินงานเรื่องร้องเรียน รอบ 12 เดือน');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 186, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 10", "MOIT10 บันทึกรายงานผลการดำเนินงานเรื่องร้องเรียน รอบ 12 เดือน", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit10_04.pdf"]', 'MOIT10 บันทึกรายงานผลการดำเนินงานเรื่องร้องเรียน รอบ 12 เดือน');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 187, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 10", "MOIT10 บันทึกรายงานผลการดำเนินงานเรื่องร้องเรียน รอบ 12M", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit10_05.pdf"]', 'MOIT10 บันทึกรายงานผลการดำเนินงานเรื่องร้องเรียน รอบ 12M');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 188, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 10", "MOIT10 แบบรายงานการจัดการเรื่องร้องเรียน 12 ด", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit10_06.docx"]', 'MOIT10 แบบรายงานการจัดการเรื่องร้องเรียน 12 ด');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 189, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 10", "MOIT10 แบบรายงานการจัดการเรื่องร้องเรียน 12 ด", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit10_07.pdf"]', 'MOIT10 แบบรายงานการจัดการเรื่องร้องเรียน 12 ด');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 190, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 11", "MOIT11 หนังสือแจ้งผู้ร้องเรียนภายใน๑๕วัน", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit11_01.docx"]', 'MOIT11 หนังสือแจ้งผู้ร้องเรียนภายใน๑๕วัน');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 191, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 11", "MOIT11 หนังสือแจ้งผู้ร้องเรียนภายใน๑๕วัน", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit11_02.pdf"]', 'MOIT11 หนังสือแจ้งผู้ร้องเรียนภายใน๑๕วัน');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 192, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 12", "1. ประกาศเจตนารมณ์ ต่อต้านการทุจริต", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit12_01.doc"]', '1. ประกาศเจตนารมณ์ ต่อต้านการทุจริต');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 193, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 12", "12 MOIT แบบฟอร์มเผยแพร่บนเว็บไซต์2569", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit12_02.docx"]', '12 MOIT แบบฟอร์มเผยแพร่บนเว็บไซต์2569');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 194, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 12", "12 MOIT แบบฟอร์มเผยแพร่บนเว็บไซต์2569", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit12_03.pdf"]', '12 MOIT แบบฟอร์มเผยแพร่บนเว็บไซต์2569');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 195, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 12", "MOIT12 บันทึกรายงานผลการดำเนินงานรายงานสรุปผลการกำกับติดตามมาตรการ การป้องกันการรับสินบน", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit12_04.doc"]', 'MOIT12 บันทึกรายงานผลการดำเนินงานรายงานสรุปผลการกำกับติดตามมาตรการ การป้องกันการรับสินบน');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 196, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 12", "MOIT12 บันทึกรายงานผลการดำเนินงานรายงานสรุปผลการกำกับติดตามมาตรการ การป้องกันการรับสินบน", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit12_05.pdf"]', 'MOIT12 บันทึกรายงานผลการดำเนินงานรายงานสรุปผลการกำกับติดตามมาตรการ การป้องกันการรับสินบน');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 197, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 12", "มาตรการ การป้องกันการรับสินบน2569", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit12_06.pdf"]', 'มาตรการ การป้องกันการรับสินบน2569');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 198, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "10 เอกสารหมายเลข 4 ปฎิญญาคุณธรรม", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_01.docx"]', '10 เอกสารหมายเลข 4 ปฎิญญาคุณธรรม');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 199, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "10 เอกสารหมายเลข 4 ปฎิญญาคุณธรรม", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_02.pdf"]', '10 เอกสารหมายเลข 4 ปฎิญญาคุณธรรม');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 200, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "11 เอกสารหมายเลข 5 ครอบครัวอบอุ่นสรรสร้างคุ", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_03.docx"]', '11 เอกสารหมายเลข 5 ครอบครัวอบอุ่นสรรสร้างคุ');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 201, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "11 เอกสารหมายเลข 5 ครอบครัวอบอุ่นสรรสร้างคุ", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_04.pdf"]', '11 เอกสารหมายเลข 5 ครอบครัวอบอุ่นสรรสร้างคุ');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 202, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "12 เอกสารหมายเลข 6 รายงานผลฯ 69", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_05.doc"]', '12 เอกสารหมายเลข 6 รายงานผลฯ 69');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 203, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "12 เอกสารหมายเลข 6 รายงานผลฯ 69", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_06.pdf"]', '12 เอกสารหมายเลข 6 รายงานผลฯ 69');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 204, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "1 MOIT16 บันทึกเสนอผู้บริหารทราบ - 1.2", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_07.docx"]', '1 MOIT16 บันทึกเสนอผู้บริหารทราบ - 1.2');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 205, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "1 MOIT16 บันทึกเสนอผู้บริหารทราบ - 1.2", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_08.pdf"]', '1 MOIT16 บันทึกเสนอผู้บริหารทราบ - 1.2');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 206, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "1 MOIT16 บันทึกเสนอผู้บริหารทราบ", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_09.docx"]', '1 MOIT16 บันทึกเสนอผู้บริหารทราบ');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 207, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "1 MOIT16 บันทึกเสนอผู้บริหารทราบ", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_10.pdf"]', '1 MOIT16 บันทึกเสนอผู้บริหารทราบ');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 208, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "8 เอกสารหมายเลข 2 แผนฯ 69", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_11.docx"]', '8 เอกสารหมายเลข 2 แผนฯ 69');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 209, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "8 เอกสารหมายเลข 2 แผนฯ 69", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_12.pdf"]', '8 เอกสารหมายเลข 2 แผนฯ 69');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 210, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "9 เอกสารหมายเลข 3 กิจกรรมพอเพียง", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_13.docx"]', '9 เอกสารหมายเลข 3 กิจกรรมพอเพียง');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 211, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "9 เอกสารหมายเลข 3 กิจกรรมพอเพียง", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_14.pdf"]', '9 เอกสารหมายเลข 3 กิจกรรมพอเพียง');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 212, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "MOIT 16 แบบฟอร์มเผยแพร่บนเว็บไซต์2569", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_15.docx"]', 'MOIT 16 แบบฟอร์มเผยแพร่บนเว็บไซต์2569');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 213, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "MOIT 16 แบบฟอร์มเผยแพร่บนเว็บไซต์2569", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_16.pdf"]', 'MOIT 16 แบบฟอร์มเผยแพร่บนเว็บไซต์2569');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 214, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "MOIT 16.2 แบบฟอร์มเผยแพร่บนเว็บไซต์2569", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_17.docx"]', 'MOIT 16.2 แบบฟอร์มเผยแพร่บนเว็บไซต์2569');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 215, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 16", "MOIT 16.2 แบบฟอร์มเผยแพร่บนเว็บไซต์2569", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit16_18.pdf"]', 'MOIT 16.2 แบบฟอร์มเผยแพร่บนเว็บไซต์2569');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 216, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 17", "MOIT17 รายงานประเมินความเสี่ยงการทุจริต 2569", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit17_01.docx"]', 'MOIT17 รายงานประเมินความเสี่ยงการทุจริต 2569');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 217, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 17", "MOIT17 รายงานประเมินความเสี่ยงการทุจริต 2569", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit17_02.pdf"]', 'MOIT17 รายงานประเมินความเสี่ยงการทุจริต 2569');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 218, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 19", "OK MOIT 19 เรี่ยไร", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit19_01.pdf"]', 'OK MOIT 19 เรี่ยไร');
INSERT OR REPLACE INTO legacy_rows (dataset, row_index, data_json, title_text) VALUES ('ITA', 219, '["ตัวชี้วัด ITA รอบ 12 เดือน ปีงบประมาณ 2569", "MOIT 22", "OK MOIT 22 รายงานผลล่วงละเมิดทางเพศ 12เดือน", "เอกสารประกอบการประเมิน ITA รอบ 12 เดือน ปีงบประมาณ 2569", "https://ittcmoph-cloud.github.io/thaijaroen/ita-12m-2569/moit22_01.pdf"]', 'OK MOIT 22 รายงานผลล่วงละเมิดทางเพศ 12เดือน');

-- Verify
SELECT dataset, COUNT(*) AS rows FROM legacy_rows WHERE dataset='ITA' GROUP BY dataset;